---
- name: restart zabbix agent
  service: name=zabbix-agent
    state=restarted

- name: restart zabbix server
  service: name=zabbix-server
    state=restarted

- name: enable and start zabbix-server
  service: name=zabbix-server
    state=started
    enabled=yes

- name: restart apache
  service: name=httpd
    state=restarted

